import assert from 'node:assert/strict';
import type { Niivue, CompletedMeasurement } from '@niivue/niivue';
import type { AnnotationHandle } from '../lib/annotation-store.ts';
import { validateAnnotations, type AnnotationRecord } from '../lib/annotations.ts';
import { bindAnnotationViewer } from '../lib/annotation-viewer.ts';
let record:AnnotationRecord={format:'nmrview-annotations',version:1,source:'scan',grid:'grid',name:'scan',dimensions:[2,2,2],frames:2,updatedAt:new Date().toISOString(),notes:'',labels:[],measurements:[],bitmap:null};
const listeners=new Set<(r:AnnotationRecord)=>void>();
const handle={get:()=>record,update:(value:AnnotationRecord)=>{record=validateAnnotations(value,value.bitmap);for(const l of [...listeners])l(record);},subscribe:(l:(r:AnnotationRecord)=>void)=>{listeners.add(l);return ()=>listeners.delete(l);},close:()=>{}} as AnnotationHandle;
function fake() {
 const n={volumes:[{frame4D:0}],document:{completedMeasurements:[],completedAngles:[]},drawBitmap:null as Uint8Array|null,onMeasurementCompleted:()=>{},onAngleCompleted:()=>{},onDrawingChanged:()=>{},onFrameChange:()=>{},drawScene:()=>{},createEmptyDrawing:()=>{n.drawBitmap=new Uint8Array(8);},drawClearAllUndoBitmaps:()=>{},drawAddUndoBitmap:()=>{},refreshDrawing:()=>{n.onDrawingChanged();},closeDrawing:()=>{n.drawBitmap=null;n.onDrawingChanged();}};
 return n as unknown as Niivue;
}
const main=fake(),comparison=fake();const errors:string[]=[];
const old=main.onDrawingChanged;
const unbindMain=bindAnnotationViewer(main,handle,()=>{},e=>errors.push(e));
const unbindComparison=bindAnnotationViewer(comparison,handle,()=>{},e=>errors.push(e));
const measurement={startMM:new Float32Array([0,0,0]),endMM:new Float32Array([1,0,0]),distance:1,sliceIndex:0,sliceType:0,slicePosition:0.5} as CompletedMeasurement;
main.onMeasurementCompleted(measurement);
assert.equal(comparison.document.completedMeasurements.length,1,'measurement reaches other viewer');
comparison.volumes[0].frame4D=1;comparison.onFrameChange(comparison.volumes[0],1);
assert.equal(comparison.document.completedMeasurements.length,0,'other frame hides measurement');
main.drawBitmap=new Uint8Array([0,1,0,0,0,0,0,0]);main.onDrawingChanged('draw');
assert.deepEqual(comparison.drawBitmap,main.drawBitmap);
assert.notEqual(comparison.drawBitmap,main.drawBitmap,'renderer buffers independent');
assert.notEqual(record.bitmap,main.drawBitmap,'record detached from mutable renderer');
main.drawBitmap[1]=0;
assert.equal(record.bitmap![1],1);
handle.update({...record,bitmap:null});
assert.equal(main.drawBitmap,null);
assert.equal(comparison.drawBitmap,null);
assert.equal(errors.length,0,'drawing notifications do not recurse');
unbindMain();unbindComparison();
assert.equal(main.onDrawingChanged,old);
assert.equal(listeners.size,0);
const rebound=bindAnnotationViewer(main,handle,()=>{},e=>errors.push(e));
main.volumes=[];
main.onMeasurementCompleted(measurement);
assert.equal(record.measurements.length,1,'old binding cannot annotate a replacement scan');
rebound();
console.log('PASS: shared measurements and labels, per-frame visibility, buffer isolation, callback-loop prevention, disposal and replaced-volume isolation.');
